### ISSUE TITLE
snapshot

### ISSUE THREAD

**Issue by jokeman33** [midnightchip/SnapBack#2]
This showed up as my original fs i thnk. what is this?

com.apple.os.update-5BF1 AND MORE 

                                          thanks for your help

**Comment by ceticdev** [comment]
Pwn20wnd changed the way snapshots are named to a dynamic format. It's normal but a dumb change nonetheless.

**Comment by Cryptiiiic** [comment]
@jokeman33 Read this ^, also closing.
