### ISSUE TITLE
Stuck on 56%. A12 iOS 12.4 (Substitute)

### ISSUE THREAD

**Issue by futureflash01** [midnightchip/SnapBack#6]
Snapback is stuck at 56% on my iPhone XR running the newest 3.7.0b1 Unc0ver jailbreak. It’s been like this for an hour. i can’t get my tweak setup back! any ideas? 
![CCC70722-9BC9-4A77-9610-7EE03B0CD349](https://user-images.githubusercontent.com/50788891/65477087-6712bd80-de42-11e9-8f3f-3f2ac85d19f3.png)

**Comment by Arthurooooo** [comment]
got the same issue, but I'm at 100%

**Comment by Samgisaninja** [comment]
This is the same issue as Samgisaninja/SuccessionRestore#64 which I've just fixed in both projects. Deployment will be interesting as midnight did not give anyone (AFAIK) access to his website before leaving. I'll see what I can do.

**Comment by futureflash01** [comment]
Oh really?? Thank you bro. I appreciate your time and effort!
